package com.myspace.sample_analytics.pojo.input;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class InputDataModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "INPUTDATAMODEL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "INPUTDATAMODEL_ID_SEQ", name = "INPUTDATAMODEL_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Customer ID")
	private java.lang.String customerId;

	@org.kie.api.definition.type.Label(value = "Source payload file name")
	private java.lang.String fileName;

	@org.kie.api.definition.type.Label(value = "Number of hosts found")
	private java.lang.Integer numberOfHosts;

	@org.kie.api.definition.type.Label(value = "Total disk space used found ")
	private java.lang.Long totalDiskSpace;

	public InputDataModel() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getFileName() {
		return this.fileName;
	}

	public void setFileName(java.lang.String fileName) {
		this.fileName = fileName;
	}

	public java.lang.Integer getNumberOfHosts() {
		return this.numberOfHosts;
	}

	public void setNumberOfHosts(java.lang.Integer numberOfHosts) {
		this.numberOfHosts = numberOfHosts;
	}

	public java.lang.Long getTotalDiskSpace() {
		return this.totalDiskSpace;
	}

	public void setTotalDiskSpace(java.lang.Long totalDiskSpace) {
		this.totalDiskSpace = totalDiskSpace;
	}

	public InputDataModel(java.lang.Long id, java.lang.String customerId,
			java.lang.String fileName, java.lang.Integer numberOfHosts,
			java.lang.Long totalDiskSpace) {
		this.id = id;
		this.customerId = customerId;
		this.fileName = fileName;
		this.numberOfHosts = numberOfHosts;
		this.totalDiskSpace = totalDiskSpace;
	}

}