package org.jboss.xavier.analytics.rules.agendafocus.reevaluate;

import java.lang.String;
import org.jboss.xavier.analytics.pojo.output.workload.inventory.WorkloadInventoryReportModel

dialect "java"
agenda-group "MAIN"

rule "AgendaFocusForReevaluate"
    when
    then
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Category").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Complexity").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("TargetsReevaluate").setFocus();
end
