package org.jboss.xavier.analytics.rules.workload.inventory;

import org.jboss.xavier.analytics.pojo.input.workload.inventory.VMWorkloadInventoryModel
import org.jboss.xavier.analytics.pojo.output.workload.inventory.WorkloadInventoryReportModel
import java.util.Date;

dialect "java"
agenda-group "BasicFields"
auto-focus true

rule "Copy basic fields and agenda controller"
    when
        vmWorkloadInventoryModel : VMWorkloadInventoryModel(
            provider != null ,
            datacenter != null,
            cluster != null,
            vmName != null,
            diskSpace != null,
            memory != null,
            cpuCores != null,
            guestOSFullName !=null,
            osProductName != null,
            product != null,
            version != null,
            host_name != null,
            scanRunDate != null
        )
    then
        WorkloadInventoryReportModel workloadInventoryReport =  new WorkloadInventoryReportModel();
        workloadInventoryReport.setProvider(vmWorkloadInventoryModel.getProvider());
        workloadInventoryReport.setDatacenter(vmWorkloadInventoryModel.getDatacenter());
        workloadInventoryReport.setCluster(vmWorkloadInventoryModel.getCluster());
        workloadInventoryReport.setVmName(vmWorkloadInventoryModel.getVmName());
        workloadInventoryReport.setDiskSpace(vmWorkloadInventoryModel.getDiskSpace());
        workloadInventoryReport.setMemory(vmWorkloadInventoryModel.getMemory());
        workloadInventoryReport.setCpuCores(vmWorkloadInventoryModel.getCpuCores());
        workloadInventoryReport.setOsDescription(vmWorkloadInventoryModel.getGuestOSFullName());
        workloadInventoryReport.setOsName(vmWorkloadInventoryModel.getOsProductName());
        workloadInventoryReport.setProduct(vmWorkloadInventoryModel.getProduct());
        workloadInventoryReport.setVersion(vmWorkloadInventoryModel.getVersion());
        workloadInventoryReport.setHost_name(vmWorkloadInventoryModel.getHost_name());
        workloadInventoryReport.setCreationDate(vmWorkloadInventoryModel.getScanRunDate());

        insert(workloadInventoryReport);
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Workloads").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Complexity").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Targets").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Flags").setFocus();
end
