package org.jboss.xavier.analytics.rules.workload.inventory;

import org.jboss.xavier.analytics.pojo.input.workload.inventory.VMWorkloadInventoryModel
import org.jboss.xavier.analytics.pojo.output.workload.inventory.WorkloadInventoryReportModel
import java.util.Date;

dialect "java"
agenda-group "BasicFields"
auto-focus true

rule "Copy basic fields and agenda controller"
    when
        vmWorkloadInventoryModel : VMWorkloadInventoryModel(
            provider != null ,
            // These fields became optional in https://issues.redhat.com/browse/MIGENG-328
            // datacenter != null,
            // cluster != null,
            vmName != null,
            diskSpace != null,
            memory != null,
            cpuCores != null,
            product != null,
            version != null,
            // This field became optional in https://issues.redhat.com/browse/MIGENG-328
            // host_name != null,
            scanRunDate != null
        )
    then
        WorkloadInventoryReportModel workloadInventoryReport =  new WorkloadInventoryReportModel();
        workloadInventoryReport.setProvider(vmWorkloadInventoryModel.getProvider());
        // It could be that, since it's an optional input field, we are setting it to null:
        // in such a case it will be up to 'ReasonableDefaults' rules it to the default value
        workloadInventoryReport.setDatacenter(vmWorkloadInventoryModel.getDatacenter());
        workloadInventoryReport.setCluster(vmWorkloadInventoryModel.getCluster());
        workloadInventoryReport.setVmName(vmWorkloadInventoryModel.getVmName());
        workloadInventoryReport.setDiskSpace(vmWorkloadInventoryModel.getDiskSpace());
        workloadInventoryReport.setMemory(vmWorkloadInventoryModel.getMemory());
        workloadInventoryReport.setCpuCores(vmWorkloadInventoryModel.getCpuCores());
        workloadInventoryReport.setOsDescription(vmWorkloadInventoryModel.getGuestOSFullName());
        workloadInventoryReport.setOsName(vmWorkloadInventoryModel.getOsProductName());
        workloadInventoryReport.setProduct(vmWorkloadInventoryModel.getProduct());
        workloadInventoryReport.setVersion(vmWorkloadInventoryModel.getVersion());
        workloadInventoryReport.setHost_name(vmWorkloadInventoryModel.getHost_name());
        workloadInventoryReport.setCreationDate(vmWorkloadInventoryModel.getScanRunDate());

        insert(workloadInventoryReport);
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Complexity").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Targets").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Workloads").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("Flags").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("OSFamily").setFocus();
        kcontext.getKieRuntime().getAgenda().getAgendaGroup("ReasonableDefaults").setFocus();
end
